apiVersion: apps/v1
kind: Deployment
metadata:
  name: zxf-java-memory-app
  labels:
    app: zxf-java-memory-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: zxf-java-memory-app
  template:
    metadata:
      labels:
        app: zxf-java-memory-app
    spec:
      containers:
        - name: zxf-java-memory-app
          image: zxf-java-memory-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: zxf-java-memory-app
  labels:
    app: zxf-java-memory-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: zxf-java-memory-app