apiVersion: apps/v1
kind: Deployment
metadata:
  name: zxf-java-memory-app
  labels:
    app: zxf-java-memory-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zxf-java-memory-app
  template:
    metadata:
      labels:
        app: zxf-java-memory-app
    spec:
      containers:
        - name: zxf-java-memory-app-container
          image: zxf-java-memory-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: zxf-java-memory-service
  labels:
    app: zxf-java-memory-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: zxf-java-memory-app