apiVersion: apps/v1
kind: Deployment
metadata:
  name: zxf-springboot-camunda-arch
  labels:
    app: zxf-springboot-camunda-arch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zxf-springboot-camunda-arch
  template:
    metadata:
      labels:
        app: zxf-springboot-camunda-arch
    spec:
      containers:
        - name: zxf-springboot-camunda-arch-app
          image: zxf-springboot-camunda-arch-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
        - name: zxf-springboot-camunda-arch-rest
          image: zxf-springboot-camunda-arch-rest:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: zxf-springboot-camunda-arch
  labels:
    app: zxf-springboot-camunda-arch
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: zxf-springboot-camunda-arch